partner:
  token: token
  urls:
    cancel_order: ${cancel_order_url}
    create_order: ${create_order_url}
    get_order: ${get_order_url}
    get_orders_status: ${get_orders_status_url}
    update_order_items: ${update_order_items_url}

    put_inbound: ${put_inbound_url}
    get_inbound: ${get_inbound_url}
    get_inbound_status: ${get_inbound_status_url}
    get_inbound_status_history: ${get_inbound_status_history_url}

    put_outbound: ${put_outbound_url}
    get_outbound: ${get_outbound_url}
    get_outbound_status: ${get_outbound_status_url}
    get_outbound_status_history: ${get_outbound_status_history_url}

    put_movement: ${put_movement_url}
    get_movement: ${get_movement_url}
    get_movement_status: ${get_movement_status_url}
    get_movement_status_history: ${get_movement_status_history_url}
